name: "Terraform Apply & CodeDeploy (Main)"
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::145250404945:role/GitHubActionsRole
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./env/dev
        run: terraform init

      - name: Terraform Apply
        working-directory: ./env/dev
        run: terraform apply -auto-approve -no-color

      - name: Extract Target Variables from Terraform
        id: get-tf-outputs
        working-directory: ./env/dev
        run: |
          ECR_URL=$(terraform output -raw ecr_repository_url)
          ARTIFACT_BUCKET=$(terraform output -raw codedeploy_s3_bucket)
          
          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV
          echo "ARTIFACT_BUCKET=$ARTIFACT_BUCKET" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        working-directory: ./app
        run: |
          docker build -t ${{ env.ECR_URL }}:latest .
          docker push ${{ env.ECR_URL }}:latest

      - name: Package CodeDeploy Artifact
        run: |
          mkdir -p deployment_artifact~

          echo "ECR_URL=${{ env.ECR_URL }}" >> deployment_artifact/.env
          echo "DB_HOST=${{ env.DB_HOST }}" >> deployment_artifact/.env
          
          cp appspec.yml deployment_artifact/
          cp -r scripts/ deployment_artifact/
          cd deployment_artifact
          zip -r ../deploy-${{ github.sha }}.zip .

      - name: Upload Artifact to S3
        run: |
          aws s3 cp deploy-${{ github.sha }}.zip s3://${{ env.ARTIFACT_BUCKET }}/deploy-${{ github.sha }}.zip

      - name: Trigger AWS CodeDeploy
        run: |
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name dev-flask-app-deploy \
            --deployment-group-name dev-deployment-group \
            --s3-location bucket=${{ env.ARTIFACT_BUCKET }},key=deploy-${{ github.sha }}.zip,bundleType=zip \
            --query "deploymentId" --output text)
            
          echo "CodeDeploy triggered with ID: $DEPLOYMENT_ID"
          
          aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_ID
          
          echo "CodeDeploy deployment successfully rolled out to EC2!"